run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Core
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - revive
    - gosec
    - gocyclo
    - depguard
    - dupl

    # SRP & maintainability
    - funlen
    - gocognit
    - nestif
    - maintidx

    # Readability & style
    - gofmt
    - goimports
    - errname
    - unparam

    # Safety / defensive coding
    - bodyclose
    - forcetypeassert
    - asasalint
    - prealloc

linters-settings:
  depguard:
    rules:
      Main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "use github.com/bborbe/errors instead"
          - pkg: "github.com/bborbe/argument"
            desc: "use github.com/bborbe/argument/v2 instead"
          - pkg: "golang.org/x/net/context"
            desc: "use context from standard library instead"
          - pkg: "golang.org/x/lint/golint"
            desc: "deprecated, use revive or staticcheck instead"
          - pkg: "io/ioutil"
            desc: "deprecated since Go 1.16, use io and os packages instead"

  funlen:
    lines: 80
    statements: 50

  gocognit:
    min-complexity: 20

  nestif:
    min-complexity: 4

  maintidx:
    min-maintainability-index: 20

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019"
    - linters:
        - revive
      path: "_test\\.go$"
      text: "dot-imports"
    - linters:
        - revive
      text: "unused-parameter"
    - linters:
        - dupl
      path: "_test\\.go$"
    - linters:
        - depguard
      text: "github.com/bborbe/argument/v2"
